In [1]:
import pandas as pd
import numpy as np

Importing Dataset

In [2]:
fifa=pd.read_csv('/kaggle/input/fifa-21-messy-raw-dataset-for-cleaning-exploring/fifa21 raw data v2.csv')
fifa

/tmp/ipykernel_20/429399412.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  fifa=pd.read_csv('/kaggle/input/fifa-21-messy-raw-dataset-for-cleaning-exploring/fifa21 raw data v2.csv')

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

Droping Unwanted Clomuns and Renameing Columns

In [3]:
fifa.shape

(18979, 77)

In [4]:
fifa.drop(columns=['Name','photoUrl','playerUrl','Nationality'],inplace=True)

In [5]:
fifa.rename(columns={'LongName':'Name'},inplace=True)
fifa.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595

Remove the unnecessary newline characters from all columns that have them.

In [6]:
fifa['Club']=fifa['Club'].str.replace('\n\n\n\n','')
fifa.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595

Convert the height and weight columns to numerical forms

In [7]:
fifa['Height']=fifa['Height'].str.replace('cm','')
fifa.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [8]:
fifa['Height'].unique()

array(['170', '187', '188', '181', '175', '184', '191', '178', '193',
       '185', '199', '173', '168', '176', '177', '183', '180', '189',
       '179', '195', '172', '182', '186', '192', '165', '194', '167',
       '196', '163', '190', '174', '169', '171', '197', '200', '166',
       '6\'2"', '164', '198', '6\'3"', '6\'5"', '5\'11"', '6\'4"',
       '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"', '5\'4"',
       '201', '158', '162', '161', '160', '203', '157', '156', '202',
       '159', '206', '155'], dtype=object)

In [9]:
def ToInteger(x):
    featInch=str(x).replace("\'",x) 
    return int(round(float(featInch[0])* 30.48 + float(featInch[1].replace('"',''))* 2.54))

fifa['Height']=fifa['Height'].apply(ToInteger)

In [10]:
fifa['Height'].head()

0    48
1    51
2    51
3    51
4    48
Name: Height, dtype: int64

Converting Weight

In [11]:
fifa['Weight'].unique()

fifa['Weight']=fifa['Weight'].str.replace('kg','')
fifa['Weight']=fifa['Weight'].str.replace('lbs','')

In [12]:
fifa.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",48,72,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,35,92,92,Juventus,2018 ~ 2022,"ST, LW",51,83,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,Jan Oblak,27,91,93,Atlético Madrid,2014 ~ 2023,GK,51,87,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",51,70,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",48,68,...,High,Medium,5 ★,91,85,86,94,36,59,595

'Value', 'Wage' and "Release Clause' are string columns. Convert them to numbers. For eg, "M" in value column is Million, so multiply the row values by 1,000,000, etc.

In [13]:
def ConvertMoney(money:str):
    if '€' in money:
        money=money.replace("€","")
    if 'M' in money:
        return int(float(money.replace('M',''))*1000000)
    elif 'K' in money:
        return int(float(money.replace('K',''))*1000)

fifa['Value'] = fifa['Value'].apply(ConvertMoney)
fifa['Wage'] = fifa['Wage'].apply(ConvertMoney)
fifa['Release Clause'] = fifa['Release Clause'].apply(ConvertMoney)
fifa[['Value','Wage','Release Clause']]

             Value      Wage  Release Clause
0      103500000.0  560000.0     138400000.0
1       63000000.0  220000.0      75900000.0
2      120000000.0  125000.0     159400000.0
3      129000000.0  370000.0     161000000.0
4      132000000.0  270000.0     166500000.0
...            ...       ...             ...
18974     100000.0    1000.0         70000.0
18975     130000.0       NaN        165000.0
18976     120000.0       NaN        131000.0
18977     100000.0    2000.0         88000.0
18978     100000.0    1000.0         79000.0

[18979 rows x 3 columns]

Covert 'Hits' into numberical forms

In [14]:
fifa['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', nan, 11.0,
       2.0, 1.0, 31.0, 3.0, 10.0, 9.0, 17.0, 7.0, 4.0, 6.0], dtype=object)

In [15]:
fifa['Hits'].apply(lambda x: float(x) if 'K' not in str(x)  else str(x).replace('K','')*1000)

0        771.0
1        562.0
2        150.0
3        207.0
4        595.0
         ...
18974      NaN
18975      NaN
18976      NaN
18977      NaN
18978      NaN
Name: Hits, Length: 18979, dtype: object

Some columns have 'star' characters. Strip those columns of these stars and make the columns numerical

In [16]:
fifa['IR']=fifa['IR'].apply(lambda x : str(x).split()[0])
fifa.head()

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",48,72,...,Medium,Low,5,85,92,91,95,38,65,771
1,20801,C. Ronaldo dos Santos Aveiro,35,92,92,Juventus,2018 ~ 2022,"ST, LW",51,83,...,High,Low,5,89,93,81,89,35,77,562
2,200389,Jan Oblak,27,91,93,Atlético Madrid,2014 ~ 2023,GK,51,87,...,Medium,Medium,3,87,92,78,90,52,90,150
3,192985,Kevin De Bruyne,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",51,70,...,High,High,4,76,86,93,88,64,78,207
4,190871,Neymar da Silva Santos Jr.,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",48,68,...,High,Medium,5,91,85,86,94,36,59,595

In [17]:
fifa[fifa['Value']==fifa['Value'].max()]

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
8,231747,Kylian Mbappé,21,90,95,Paris Saint-Germain,2018 ~ 2022,"ST, LW, RW",48,73,...,High,Low,3,96,86,78,91,39,76,1.6K

Based on the 'Joined' column, check which players have been playing at a club for more than 10 years!

In [18]:
fifa[fifa['Joined'].apply(lambda x:(2024-int(str(x).split(',')[1]))>10)]

,ID,Name,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",48,72,...,Medium,Low,5,85,92,91,95,38,65,771
12,200145,Carlos Henrique Venancio Casimiro,28,89,89,Real Madrid,2013 ~ 2023,CDM,51,84,...,High,High,3,65,73,76,72,86,91,175
14,167495,Manuel Neuer,34,89,89,FC Bayern München,2011 ~ 2023,GK,53,92,...,Medium,Medium,5,87,87,91,89,57,86,118
15,165153,Karim Benzema,32,89,89,Real Madrid,2009 ~ 2022,"CF, ST",51,81,...,Medium,Low,4,74,85,81,86,40,76,216
16,155862,Sergio Ramos García,34,89,89,Real Madrid,2005 ~ 2021,CB,51,82,...,High,Medium,4,71,70,76,73,88,85,212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17186,182037,Hanlin Yao,35,56,56,Wuhan Zall,2010 ~ 2020,"CM, RW, RM",48,60,...,Medium,Medium,1,47,57,62,55,44,53,NaN
17258,222279,Feiya Chang,27,56,57,Guangzhou R&F FC,2013 ~ 2020,"ST, LW, RM",51,65,...,Medium,Medium,1,75,48,52,59,37,48,NaN
17500,235061,Omar Al Sunain,25,56,60,Ettifaq FC,2013 ~ 2023,RB,46,71,...,High,Medium,1,77,27,42,53,52,61,NaN
17863,182471,Shoubo Sun,37,55,55,Wuhan Zall,2013 ~ 2020,GK,53,80,...,Medium,Medium,1,52,52,57,52,46,63,NaN
18416,240460,Basil Al Bahrani,25,52,58,Al Fateh,2013 ~ 2022,GK,48,78,...,Medium,Medium,1,53,55,46,51,26,50,NaN

Creating Separate Column Called "YearsOfPlaying"

In [19]:
fifa['YearsOfPlaying']=fifa['Joined'].apply(lambda x:2023-(int(str(x).split(',')[1])))
fifa[['Name','Club','YearsOfPlaying']]

                               Name                 Club  YearsOfPlaying
0                      Lionel Messi         FC Barcelona              19
1      C. Ronaldo dos Santos Aveiro             Juventus               5
2                         Jan Oblak      Atlético Madrid               9
3                   Kevin De Bruyne      Manchester City               8
4        Neymar da Silva Santos Jr.  Paris Saint-Germain               6
...                             ...                  ...             ...
18974                        Ao Xia           Wuhan Zall               5
18975                     Ben Hough      Oldham Athletic               3
18976                Ronan McKinley           Derry City               4
18977                  Zhen'ao Wang     Dalian YiFang FC               3
18978                     Xiao Zhou     Dalian YiFang FC               4

[18979 rows x 3 columns]